name: accident_detection
description: Accident detection in Flutter using TensorFlow Lite
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.6
  collection: ^1.16.0
  image: ^3.2.2
  tflite_flutter: ^0.9.0
  tflite_flutter_helper:
    git:
      url: https://github.com/filofan1/tflite_flutter_helper.git
      ref: 783f15e5a87126159147d8ea30b98eea9207ac70
  flutter_barcode_scanner: ^2.0.0
  flutter_svg: ^1.1.6
  geolocator: ^11.1.0
  google_sign_in: ^6.1.6
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0


dependency_overrides:
  ffi: ^1.0.0



dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:  
  - family: SquadaOne
    fonts:
      - asset: assets/SquadaOne-Regular.ttf
  - family: ContrailOne
    fonts:
      - asset: assets/ContrailOne-Regular.ttf
  - family: Roboto
    fonts:
      - asset: assets/Roboto-Light.ttf      
  
  assets:
    - assets/
    - assets/images/
